import { StyleSheet } from "react-native";

export const LoginFormStyles = StyleSheet.create({
  container: {
    backgroundColor: "#FFF",
    height: "58%",
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    position: "absolute",
    zIndex: 3,
    bottom: 0,
    width: "100%",
    flex: 1,
    alignItems: "center",
  },
  input: {
    height: 50,
    width: "70%",
    borderColor: "black",
    borderWidth: 1,
    borderTopLeftRadius: 5,
    borderTopRightRadius: 5,
    borderBottomLeftRadius: 5,
    borderBottomRightRadius: 5,
    marginTop: 25,
    paddingLeft: 10,
  },
  inputError: {
    height: 50,
    width: "70%",
    borderColor: "red",
    borderWidth: 2,
    borderTopLeftRadius: 5,
    borderTopRightRadius: 5,
    borderBottomLeftRadius: 5,
    borderBottomRightRadius: 5,
    marginTop: 25,
    paddingLeft: 10,
  },
  invalidInput: {
    marginTop: 5,
  },
  switchContainer: {
    flex: 1,
    flexDirection: "row",
    marginBottom: 0,
  },
  loginButton: {
    marginTop: 35,
    width: "65%",
    backgroundColor: "#149de1",
    height: 50,
    color: "red",
    alignItems: "center",
    justifyContent: "center",
    borderTopLeftRadius: 50,
    borderTopRightRadius: 50,
    borderBottomLeftRadius: 50,
    borderBottomRightRadius: 50,
  },
  loginText: {
    fontSize: 20,
    fontWeight: "700",
  },
});
